### ISSUE TITLE
Window closes when i say the wake word

### ISSUE THREAD

**Issue by Legende04** [antmannacho/Jarvis-ChatGPT-VoiceAssistant#2]
**Describe the bug**
I executed the install file, then the run file, inserted the api key and now as soon as I say the wake word "jarvis" or "computer" which is the one i changed it to, but this doesnt matter the same thing happens with any of the words, it closes without telling me anything.
For a unreadable time there is something displayed, but i cant find any log file etc.

**Expected behavior**
It should answer to questions

**Screenshots**

https://github.com/antmannacho/Jarvis-ChatGPT-VoiceAssistant/assets/74209062/c434492d-c124-4ae8-b3b4-4524218dc8f0

**Desktop (please complete the following information):**
Windows 10 Desktop

btw i love your work, because i came up with the idea but it didn't seem to be very popular even though its amazing

**Comment by antmannacho** [comment]
So OpenAI changed their api format, you can edit the batch file and have it execute the exact OpenAI pinned dependency, here’s what you should change it to, I’ll work on updating the code to support the most api later today. 

Change openai to openai==0.28.1
